webportal/views.py
from datetime import date, datetime
import pyqrcode
import logging
import ipaddress
from decimal import Decimal
from io import BytesIO
from .utils.interact_db import update_db, update_db_no_close
from webportal.models.Transaction import Transaction
from flask import Blueprint, redirect, url_for, render_template, request, session, abort, jsonify, escape
from flask_login import login_required, login_user, logout_user
from webportal import flask_bcrypt, login_manager
from webportal.models.Transferee import Transferee
from .forms import *
from .utils.messaging import *
from functools import wraps
from webportal.controllers.MessageManagementController import MessageManagementController
from webportal.controllers.AccountManagementController import AccountManagementController
from webportal.controllers.EmailManagementController import EmailManagementController
from webportal.controllers.BankAccountManagementController import BankAccountManagementController
from flask.typing import ResponseReturnValue
from werkzeug.wrappers import Response

views = Blueprint('views', __name__)
TWO_PLACES = Decimal(10) ** -2


def check_email_verification(func) -> [Response]:
    @wraps(func)
    def decorated_function(*args, **kwargs):
        if current_user.email_verified is False:
            return redirect(url_for('views.unverified_email'))
        return func(*args, **kwargs)

    return decorated_function


@login_manager.user_loader
def load_user(session_token: int) -> User:
    return User.query.filter_by(session_token=session_token).first()


@views.route('/', methods=['GET'])
def home() -> ResponseReturnValue:
    if current_user.is_authenticated:
        msg_data = load_nav_messages()
        return render_template('home.html', title="Home Page", msg_data=msg_data)
    return render_template('home.html', title="Home Page")


@views.route('/about', methods=['GET'])
def about() -> ResponseReturnValue:
    if current_user.is_authenticated:
        msg_data = load_nav_messages()
        return render_template('home.html', title="Home Page", msg_data=msg_data)
    return render_template('about.html', title="About")


@views.route('/timeout', methods=['GET'])
def timeout() -> [Response, ResponseReturnValue]:
    if current_user.is_authenticated:
        return redirect(url_for('views.logout'))
    session.clear()
    return render_template('timeout.html')


@views.route('/register', methods=['GET', 'POST'])
def register() -> [Response, ResponseReturnValue]:
    ip_source = ipaddress.IPv4Address(request.remote_addr)

    if current_user.is_authenticated:
        if current_user.is_admin:
            return redirect(url_for('views.admin_dashboard'))
        return redirect(url_for('views.dashboard'))

    form = RegisterForm()
    if request.method == 'POST' and form.validate_on_submit():
        mmc = MessageManagementController()
        emc = EmailManagementController()
        amc = AccountManagementController()
        bamc = BankAccountManagementController()

        username = escape(form.username.data)
        firstname = escape(form.firstname.data)
        lastname = escape(form.lastname.data)
        address = escape(form.address.data)
        email = escape(form.email.data)
        mobile = escape(form.mobile.data)
        nric = escape(form.nric.data.upper())
        dob = form.dob.data
        age = date.today().year - dob.year
        password = flask_bcrypt.generate_password_hash(form.password.data)

        check, register_error = amc.verify_details(username, email, mobile, nric, dob, age)
        if check:
            return render_template('register.html', title="Register", form=form, register_error=register_error)

        logger = logging.getLogger('user_activity_log')
        logger.propagate = False

        amc.add_user(username, firstname, lastname, address, email, mobile, nric, dob, password, None, None, 0)

        logger.info(f"src_ip {ip_source} -> {username} user account created")

        user = User.query.filter_by(username=username).first()

        acc_number, welcome_amt = bamc.add_bank_account(user.id)

        mmc.send_welcome_msg(welcome_amt, user)

        logger.info(f"src_ip {ip_source} -> Bank acc {acc_number} created and linked to {username}")

        session['username'] = username
        token = emc.generate_token(username, user)
        confirm_url = url_for('views.confirm_email', token=token, _external=True)
        emc.send_email(email, "HX-Bank - Email Verification",
                       render_template('/email_templates/activate.html', confirm_url=confirm_url))
        return redirect(url_for("views.otp_setup"))
    return render_template('register.html', title="Register", form=form)


@views.route('/confirm/<token>')
def confirm_email(token) -> [Response, ResponseReturnValue]:
    emc = EmailManagementController()
    try:
        email = emc.confirm_token(token)
        if emc.verify_token(email, token):
            if 'username' in session:
                pass
            return redirect(url_for('views.login'))
        else:
            abort(404)
    except:
        abort(404)


@views.route('/otp-setup')
def otp_setup() -> [Response, ResponseReturnValue]:
    if 'username' not in session:
        return redirect(url_for('views.login'))

    if current_user.is_authenticated:
        return redirect(url_for('views.dashboard'))

    user = User.query.filter_by(username=session['username']).first()
    if user is None:
        return redirect(url_for('views.login'))

    return render_template('otp-setup.html'), 200, {
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}


@views.route('/qrcode')
def qrcode() -> [Response, ResponseReturnValue]:
    mmc = MessageManagementController()
    emc = EmailManagementController()
    amc = AccountManagementController()

    if 'username' not in session:
        abort(404)

    if current_user.is_authenticated:
        return redirect(url_for('views.dashboard'))

    user = User.query.filter_by(username=session['username']).first()
    if user is None:
        abort(404)

    if user.prev_token is not None:
        if 'flag' not in session:
            session.clear()
            return redirect(url_for("views.login"))
        del session['flag']
        emc.send_email(user.email, "HX-Bank - OTP Reset",
                       render_template('/email_templates/reset.html', reset="OTP",
                                       time=datetime.now().strftime('%Y-%m-%d %H:%M:%S')))
        mmc.send_otp_reset(user)

    amc.generate_pyotp(user)
    del session['username']
    url = pyqrcode.create(user.get_totp_uri())
    stream = BytesIO()
    url.svg(stream, scale=3)
    session.clear()
    return stream.getvalue(), 200, {
        'Content-Type': 'image/svg+xml',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
        'Pragma': 'no-cache',
        'Expires': '0'}


@views.route('/login', methods=['GET', 'POST'])
def login() -> [Response, ResponseReturnValue]:
    amc = AccountManagementController()

    ip_source = ipaddress.IPv4Address(request.remote_addr)

    logger = logging.getLogger('auth_log')
    logger.propagate = False
    if current_user.is_authenticated:
        logger.info(f"src_ip {ip_source} -> {current_user.username} user account successfully logged in")
        if current_user.is_admin:
            return redirect(url_for('views.admin_dashboard'))
        return redirect(url_for('views.dashboard'))

    form = LoginForm()
    error = "Login Failed"

    if request.method == 'POST' and form.validate_on_submit():
        user = User.query.filter_by(username=escape(form.username.data)).first()
        password = form.password.data

        if user:
            auth = amc.authenticate(user, password)
            if auth == 1:
                session['username'] = user.username
                return redirect(url_for('views.otp_input'))
            elif auth == 2:
                error = "Account has been locked out. Please contact customer support for assistance."
                return render_template('login.html', title="Login", form=form, login_error=error)
            elif auth == 3:
                logger.warning(f"src_ip {ip_source} -> {user.username} user account failed to login")
                return render_template('login.html', title="Login", form=form, login_error=error)
            else:
                logger.warning(f"src_ip {ip_source} -> {user.username} user account has been locked out")
                error = "Account has been locked out. Please contact customer support for assistance."
                return render_template('login.html', title="Login", form=form, login_error=error)
        else:
            return render_template('login.html', title="Login", form=form, login_error=error)
    return render_template('login.html', title="Login", form=form)


@views.route('/logout', methods=['GET', 'POST'])
@login_required
def logout() -> ResponseReturnValue:
    ip_source = ipaddress.IPv4Address(request.remote_addr)
    logger = logging.getLogger('auth_log')
    logger.propagate = False
    logger.info(f"src_ip {ip_source} -> {current_user.username} user account successfully logged out")
    logout_user()
    session.clear()
    return redirect(url_for('views.login'))


@views.route('/otp-input', methods=['GET', 'POST'])
def otp_input() -> [Response, ResponseReturnValue]:
    mmc = MessageManagementController()
    amc = AccountManagementController()

    ip_source = ipaddress.IPv4Address(request.remote_addr)

    logger = logging.getLogger('auth_log')
    logger.propagate = False

    if 'username' not in session:
        session.clear()
        return redirect(url_for('views.login'))

    if current_user.is_authenticated:
        if current_user.is_admin:
            return redirect(url_for('views.admin_dashboard'))
        return redirect(url_for('views.dashboard'))

    form = Token2FAForm()
    error = "Invalid Token"

webportal/templates/includes/footer.html
<footer class="footer-area bg-secondary">
    <div class="copyright__area">
        <div class="container">
            <div class="col-sm-12">
                <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                    {% if not current_user.is_authenticated %}
                    <li class="nav-item"><a href="{{ url_for('views.home') }}" class="nav-link px-2 text-white">Home</a></li>
                    {% elif current_user.is_authenticated and not current_user.is_admin %}
                    <li class="nav-item"><a href="{{ url_for('views.dashboard') }}" class="nav-link px-2 text-white">Home</a></li>
                    {% elif current_user.is_authenticated and current_user.is_admin %}
                    <li class="nav-item"><a href="{{ url_for('views.admin_dashboard') }}" class="nav-link px-2 text-white">Home</a></li>
                    {% endif %}
                    <li class="nav-item"><a href="{{ url_for('views.about') }}" class="nav-link px-2 text-white">About Us</a></li>
                </ul>
                <p class="copyright_text text-white text-center">
                    Copyright &copy; 2022 HXBank. All Rights Reserved
                </p>
            </div>
        </div>
    </div>
</footer>

webportal/templates/includes/navigation.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="container">
        {% if not current_user.is_authenticated %}
        <a class="navbar-brand w-50 me-auto" href="{{ url_for('views.home') }}">HX-Bank</a>
        {% elif current_user.is_authenticated and not current_user.is_admin %}
        <a class="navbar-brand w-50 me-auto" href="{{ url_for('views.dashboard') }}">HX-Bank</a>
        {% elif current_user.is_authenticated and current_user.is_admin %}
        <a class="navbar-brand w-50 me-auto" href="{{ url_for('views.admin_dashboard') }}">HX-Bank</a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
                aria-controls="navbar"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse pl-3 pl-lg-0 w-100" id="navbar">
            <ul class="navbar-nav mt-2 mt-lg-0 w-80 justify-content-center">
                {% if current_user.is_authenticated and not current_user.is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.transaction_history') }}">Transaction History</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userTransferDropdown" role="button"
                       data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Transfer
                    </a>
                    <div class="dropdown-menu dropdown-menu-dark" aria-labelledby="userTransferDropdown">
                        <a class="dropdown-item" href="{{ url_for('views.transfer') }}">Transfer to another account</a>
                        <a class="dropdown-item" href="{{ url_for('views.transfer_onetime') }}">Transfer to another
                            account (One-Time)</a>
                        <a class="dropdown-item" href="{{ url_for('views.add_transferee') }}">Add Transfer Recipient</a>
                        <div class="dropdown-divider border border-secondary"></div>
                        <a class="dropdown-item" href="{{ url_for('views.set_transfer_limit') }}">Set Transfer Limit</a>
                        <a class="dropdown-item" href="{{ url_for('views.view_transferee') }}">View Transfer
                            Recipients</a>
                        <a class="dropdown-item" href="{{ url_for('views.topup_balance') }}">Top Up Balance</a>
                    </div>
                </li>
                {% elif current_user.is_authenticated and current_user.is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.transaction_management') }}">Transaction Management</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.enrol_admin') }}">Enrol Admin</a>
                </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav ms-auto w-80 justify-content-end">
                {% if not current_user.is_authenticated %}
                {% block nav_about %}
                    <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                    </li>
                {% endblock %}
                {% block nav_login %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.login') }}">Login</a>
                </li>
                {% endblock %}
                {% block nav_register %}
                <li class="nav-item">
                    <a class="btn btn__primary" href="{{ url_for('views.register') }}">Open Account</a>
                </li>
                {% endblock %}
                {% endif %}
                {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="notificationDropdown" role="button" data-bs-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {% if msg_data %}
                        <span class="material-icons md-light">notifications_active</span>
                        {% else %}
                        <span class="material-icons md-light">notifications_none</span>
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end"
                         aria-labelledby="notificationDropdown">
                        {% if msg_data %}
                        {% for msg in msg_data %}
                        {% if loop.index <= 5 %}
                        <p class="dropdown-item {{ 'text-muted' if msg.read else 'text-white' }}">
                            {% if not msg.read %}
                            <span class="material-icons md-18 md-light align-middle">priority_high</span>
                            {% endif %}
                            {{ msg.message|truncate(42, True) }}
                        </p>
                        <div class="dropdown-divider border border-secondary"></div>
                        {% endif %}
                        {% endfor %}
                        {% else %}
                        <p class="dropdown-item text-center">You have no new Messages!</p>
                        {% endif %}
                        <a class="dropdown-item text-center" href="{{ url_for('views.message_center') }}">View All
                            Message(s)</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('views.acc_settings') }}"><span
                            class="material-icons md-light">settings</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        <span class="material-icons md-light">account_circle</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="profileDropdown">
                        <a class="dropdown-item" href="{{ url_for('views.profile') }}">{{ current_user.username }}</a>
                        <a class="dropdown-item" href="{{ url_for('views.message_center') }}">Message Center</a>
                        <div class="dropdown-divider border border-secondary"></div>
                        <a class="dropdown-item" href="{{ url_for('views.logout') }}">Logout</a>
                    </div>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

webportal/templates/includes/transaction_nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="#">All</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Received</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Transfer</a>
      </li>
    </ul>
  </div>
</nav>